"use client";

import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { TreePalm, User } from "lucide-react";
import Image from "next/image";

type FormValues = {
  name: string;
  email: string;
  location: string;
  interests: string;
};

export default function UserForm() {
  const [success, setSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [recommendation, setRecommendation] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<FormValues>();

  const onSubmit = async (formData: FormValues) => {
    setLoading(true);
    setSuccess(false);
    setRecommendation(null);

    try {
      const res = await fetch("/api/mcp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          interests: formData.interests.split(",").map(i => i.trim()),
        }),
      });

      const data = await res.json();

      if (!res.ok) {
         throw new Error(data.error || `HTTP error! status: ${res.status}`);
      }

      // Read the tool execution result generated by Gemini
      let aiText = "The Orchestrator successfully analyzed your profile, but returned no text.";
      
      if (data.mcpResult) {
         if (typeof data.mcpResult === 'string') {
             aiText = data.mcpResult;
         } else if (data.mcpResult?.result?.content?.[0]?.text) {
             aiText = data.mcpResult.result.content[0].text;
         } else if (data.mcpResult?.text) {
             aiText = data.mcpResult.text;
         } else if (data.mcpResult?.response) {
             aiText = data.mcpResult.response;
         }
      }

      setRecommendation(aiText);
      setSuccess(true);
      reset();
    } catch (err: any) {
      console.error("Failed to execute webhook", err);
      alert("Error: Something broke in the Next.js API. Check the logs. " + (err.message || err));
      setSuccess(false);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center min-h-screen bg-[#0B0F19] text-white font-sans w-full p-6 pt-12 overflow-hidden relative selection:bg-teal-500/30">
      
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-900/10 rounded-full blur-[100px] pointer-events-none"></div>

      <div className="w-full max-w-[360px] relative z-10 flex flex-col items-center">
        
        {/* Top Header */}
        <div className="w-full flex justify-between items-center mb-8 px-1">
          <TreePalm className="w-5 h-5 text-white/70" />
          <span className="text-white/60 text-xs font-medium tracking-wide">Sun, Apr 19</span>
          <div className="w-7 h-7 rounded-full bg-white/5 border border-white/10 flex items-center justify-center overflow-hidden">
             <User className="w-3.5 h-3.5 text-white/60"/>
          </div>
        </div>
        
        {/* Illustration Container */}
        <div className="w-full rounded-[2rem] overflow-hidden shadow-2xl mb-0 relative border border-white/5 h-[200px]">
          <div className="absolute inset-0 bg-gradient-to-t from-[#0B0F19] via-[#0B0F19]/20 to-transparent z-10"></div>
          <Image 
            src="/beach_shack.png" 
            alt="Night beach shack" 
            fill
            className="object-cover opacity-90 scale-105"
            priority
          />
        </div>

        {/* Dynamic Text Area based on state */}
        <div className="text-center w-full z-20 -mt-12 mb-6">
          <h1 className="text-[28px] font-serif mb-1.5 tracking-tight text-white/90">
            {success ? "Events Found" : "Good night, saim"}
          </h1>
          <p className="text-white/40 text-xs tracking-wide">
            {success ? "Orchestrator curated your events" : "Enter your vibe below"}
          </p>
        </div>

        {/* If successfully generated, show the AI recommendation. Otherwise show Form. */}
        {success && recommendation ? (
            <div className="w-full p-5 bg-[#181C26] border border-white/[0.04] rounded-2xl animate-in fade-in slide-in-from-bottom-2">
                <p className="text-white/80 text-sm leading-relaxed whitespace-pre-wrap font-sans">
                  {recommendation}
                </p>
                <button
                  onClick={() => { setSuccess(false); setRecommendation(null); }}
                  className="mt-6 w-full py-3 bg-white/5 hover:bg-white/10 border border-white/10 text-white/90 text-xs font-medium rounded-xl transition-all"
                >
                  Start Over
                </button>
            </div>
        ) : (
        <form onSubmit={handleSubmit(onSubmit)} className="w-full grid grid-cols-2 gap-3 z-20">
          <div className="col-span-2 relative group">
            <input
              {...register("name", { required: "Required" })}
              placeholder="Name"
              className="w-full bg-[#181C26] group-hover:bg-[#1E232F] transition-colors border border-white/[0.04] rounded-2xl px-5 py-4 focus:outline-none focus:ring-1 focus:ring-white/10 text-sm placeholder:text-white/30 text-center"
            />
          </div>

          <div className="col-span-1 relative group">
            <input
              {...register("email", { required: "Required" })}
              type="email"
              placeholder="Email"
              className="w-full bg-[#181C26] group-hover:bg-[#1E232F] transition-colors border border-white/[0.04] rounded-2xl px-4 py-4 focus:outline-none focus:ring-1 focus:ring-white/10 text-xs placeholder:text-white/30 text-center"
            />
          </div>

          <div className="col-span-1 relative group">
            <input
              {...register("location", { required: "Required" })}
              placeholder="Location"
              className="w-full bg-[#181C26] group-hover:bg-[#1E232F] transition-colors border border-white/[0.04] rounded-2xl px-4 py-4 focus:outline-none focus:ring-1 focus:ring-white/10 text-xs placeholder:text-white/30 text-center"
            />
          </div>

          <div className="col-span-2 relative group">
            <input
              {...register("interests", { required: "Required" })}
              placeholder="Your Interests (e.g. coffee, hiking, indie)"
              className="w-full bg-[#181C26] group-hover:bg-[#1E232F] transition-colors border border-white/[0.04] rounded-2xl px-5 py-4 focus:outline-none focus:ring-1 focus:ring-white/10 text-xs placeholder:text-white/30 text-center"
            />
          </div>

          <div className="col-span-2 mt-2">
             <button
              type="submit"
              disabled={loading}
              className="w-full py-4 bg-white/5 hover:bg-white/10 border border-white/10 text-white/90 text-sm font-medium rounded-2xl transition-all active:scale-[0.98] disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {loading ? (
                <div className="w-4 h-4 border-2 border-white/30 border-t-white/90 rounded-full animate-spin"></div>
              ) : (
                "Initiate Orchestrator"
              )}
            </button>
          </div>
        </form>
        )}

      </div>
    </div>
  );
}
